import { getAdminI18n } from '@/lib/admin/i18n-server'
export default async function ContributorConversationGuide() {
  const { t } = await getAdminI18n()
  return <main className="admin-main admin-guide"><header className="admin-heading"><div><p className="eyebrow">{t('Internal guide')}</p><h1>{t('Contributor Conversation')}</h1><p>{t('A human conversation for mutual orientation—not a traditional interview, assessment center, recording session, or Agent input.')}</p></div></header>
    <section><h2>{t('Purpose')}</h2><p>{t('Introduce Rein, its Mission, current people, public activity, and ways to participate. Learn what the applicant cares about and what responsibility they want. Leave with a clear next step even when no immediate project is available.')}</p><p><strong>{t('Maximum duration:')}</strong> {t('30 minutes. Do not record or automatically transcribe. Do not send notes or meeting content to the Agent. The host alone decides the post-meeting outcome.')}</p></section>
    <section><h2>{t('30-minute agenda')}</h2><ol className="conversation-agenda"><li><time>{t('0–5 min')}</time><span>{t('Introduce Rein, the Mission, the participation model, and the non-legal nature of Contributor status.')}</span></li><li><time>{t('5–15 min')}</time><span>{t('Learn about the applicant’s background, interests, desired involvement, and preferred ways of working.')}</span></li><li><time>{t('15–25 min')}</time><span>{t('Introduce relevant people, public activities, current work, GitHub paths, and possible contribution directions.')}</span></li><li><time>{t('25–30 min')}</time><span>{t('Answer questions and agree on a next step.')}</span></li></ol></section>
    <section><h2>{t('Organization introduction points')}</h2><ul><li>{t('The constructive obligation: help AI Agents create public good through open knowledge and responsible practice.')}</li><li>{t('The protective obligation: preserve human life, agency, institutions, and the ability to govern an AGI/ASI future.')}</li><li>{t('Most learning and public events are open; applying is for deeper responsibility.')}</li><li>{t('Public Participant, Community Participant, Contributor, Core Contributor, and Board/Officer are different categories.')}</li><li>{t('Contributor status does not create legal membership, employment, governance, ownership, Token, agency, or tax rights.')}</li><li>{t('Current Work and public People profiles are separate, and no project assignment is promised.')}</li></ul></section>
    <section><h2>{t('Suggested questions')}</h2><ul><li>{t('What brought you to AI Agents or to the public-benefit part of this work?')}</li><li>{t('What kind of people or problems would you most like to learn alongside?')}</li><li>{t('Is there a resource, activity, or technical problem you already want to explore?')}</li><li>{t('Would you rather begin through a public activity, a bounded contribution, or ongoing responsibility?')}</li><li>{t('What would make participation useful and respectful for you?')}</li><li>{t('What questions or concerns do you have about the organization?')}</li></ul></section>
    <section><h2>{t('Low-barrier acceptance philosophy')}</h2><p>{t('Welcome people from different industries, educational backgrounds, nationalities, political or cultural backgrounds, professional paths, technical seniority, and levels of public influence. Limited English fluency, awkward phrasing, disagreement, or criticism are not rejection grounds. A lack of an immediately available project is not a rejection ground; invite broader community participation first.')}</p></section>
    <section><h2>{t('Conduct and rejection standards')}</h2><p>{t('Base a negative decision on documented conduct, never a vague label such as “extremist.” Relevant conduct includes explicit threats or encouragement of violence; hate, targeted harassment, sustained insults, or intimidation; fraud, impersonation, or malicious social engineering; doxxing, deliberate event-safety disruption, or explicit sabotage; and persistent refusal to respect basic communication and safety boundaries.')}</p></section>
    <section><h2>{t('Required post-meeting record')}</h2><ol><li>{t('Set')} <code>meeting_scheduled</code> {t('when a time is confirmed.')}</li><li>{t('After the meeting, add concise factual notes that are necessary for administration; do not create a transcript.')}</li><li>{t('Set')} <code>conversation_complete</code> {t('and record the host’s outcome.')}</li><li>{t('Create the Contributor record, return the person to broader community participation, or set')} <code>closed</code> {t('with the 12-month retention date.')}</li><li>{t('Document conduct evidence if a safety boundary affected the decision.')}</li></ol></section>
  </main>
}
