import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { CommunityPageHero, CommunitySection } from '@/components/community-shell'
import { getPublishedEvent } from '@/lib/community/data'

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const event = await getPublishedEvent(slug); return event ? { title: event.title, description: event.summary } : { title: 'Event not found' } }

export default async function EventPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const event = await getPublishedEvent(slug)
  if (!event) notFound()
  const sessions = [...event.event_sessions].sort((a, b) => new Date(a.starts_at).getTime() - new Date(b.starts_at).getTime())
  return <main id="main-content" className="community-shell"><CommunityPageHero eyebrow={`Gather / ${event.relationship === 'Beneficence-hosted' ? 'Rein-hosted' : event.relationship}`} title={event.title} lead={event.summary} /><CommunitySection eyebrow="Event details" title="Schedule and participation."><article className="event-detail">{event.image_url ? <figure className="event-detail__image"><img src={event.image_url} alt={event.image_alt ?? ''} />{event.image_source ? <figcaption>Image source: {event.image_source}</figcaption> : null}</figure> : null}<dl className="event-detail__facts"><div><dt>Format</dt><dd>{event.format.replace('_', ' ')}</dd></div><div><dt>Status</dt><dd>{event.attendance_status}</dd></div><div><dt>Timezone</dt><dd>{event.timezone}</dd></div><div><dt>Location</dt><dd>{[event.city, event.state_region, event.country].filter(Boolean).join(', ') || 'Online'}</dd></div>{event.attendance_limit ? <div><dt>Attendance limit</dt><dd>{event.attendance_limit}</dd></div> : null}{event.venue_description ? <div><dt>Venue</dt><dd>{event.venue_description}</dd></div> : null}{event.organizers ? <div><dt>Organizers</dt><dd>{event.organizers}</dd></div> : null}{event.partners ? <div><dt>Partners</dt><dd>{event.partners}</dd></div> : null}{event.conference_relationship ? <div><dt>Conference relationship</dt><dd>{event.conference_relationship}</dd></div> : null}</dl><h2>Sessions</h2><ol>{sessions.map((session) => <li key={session.starts_at}>{new Intl.DateTimeFormat('en-US', { dateStyle: 'full', timeStyle: 'short', timeZone: event.timezone }).format(new Date(session.starts_at))}–{new Intl.DateTimeFormat('en-US', { timeStyle: 'short', timeZone: event.timezone }).format(new Date(session.ends_at))} ({event.timezone})</li>)}</ol>{event.body ? <p>{event.body}</p> : null}<a className="primary-action" href={event.external_registration_url} target="_blank" rel="noreferrer">Register on the external event platform <span aria-hidden="true">↗</span></a><p className="field-hint">Registration and attendance details are managed by the external platform.</p></article></CommunitySection></main>
}
